-- Insert Sample Data
INSERT INTO students VALUES
(1, 'Arun', 'Chennai', 85),
(2, 'Vignesh', 'Madurai', 90),
(3, 'Kumar', 'Chennai', 70),
(4, 'Divya', 'Coimbatore', 95),
(5, 'Sneha', 'Madurai', 60),
(6, 'Rahul', 'Chennai', 75),
(7, 'Anu', 'Coimbatore', 88),
(8, 'Priya', 'Chennai', 92),
(9, 'Karthik', 'Madurai', 67),
(10, 'Meena', 'Coimbatore', 78);